/*
 * Interrupt_Config.h
 *
 *  Created on: Aug 23, 2023
 *      Author: orabi
 */

#ifndef INTERRUPT_CONFIG_H_
#define INTERRUPT_CONFIG_H_

#define GLOBAL_INTERRUPT_STATUS  GENERAL_INTERRUPT_ENABLE
#define INTERRUPT0_TRIGGER   	 INTERRUPT_TRIGGER_FALLING_EDGE
#define INTERRUPT1_TRIGGER   	 INTERRUPT_TRIGGER_RISING_EDGE
//NOTE THAT INTERRUPT2 WORKS ONLY IN ( FALLING EDGE , RISING EDGE )
#define INTERRUPT2_TRIGGER   	 INTERRUPT_TRIGGER_FALLING_EDGE

#endif /* INTERRUPT_CONFIG_H_ */
